apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: whisperbot
  name: whisperbot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: whisperbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisperbot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: JID
          value: "transcribe@christofschulze.com"
        - name: WHISPER_MODEL
          value: "small"
        - name: NICK
          value: "Transcribe"
        - name: ROOM
          value: kpc@muc.christofschulze.com
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: whisperbot
              key: XMPP_PASS
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: whisperbot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cache
          name: modelcache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: modelcache
        persistentVolumeClaim:
          claimName: whisperbot-model-cache

