apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: whisperbot
  name: whisperbot-model-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-nas

